name: Tests

on:
  push:
    branches: 
      - master
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build_image:
    name: Build the image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t test .
